version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - ./postgres_database:/var/lib/postgresql/data
    expose:
      - '5432'
    networks:
      - node_template

networks:
  node_template:
    driver: bridge

volumes:
  postgres_database: